'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let books=[],cryptoKey,current=null,page=1,activeCategory='',onlyFavorites=false,sequence=0;
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
let favorites=new Set(readJSON('architecture-favorites',[])),progress=readJSON('architecture-progress',{});
const cache=new Map(),pending=new Map();
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
async function decrypt(url){const r=await fetch(url);if(!r.ok)throw new Error('读取失败 '+r.status);const b=new Uint8Array(await r.arrayBuffer());return crypto.subtle.decrypt({name:'AES-GCM',iv:b.slice(0,12)},cryptoKey,b.slice(12))}
async function asset(path){if(cache.has(path)){const u=cache.get(path);cache.delete(path);cache.set(path,u);return u;}if(pending.has(path))return pending.get(path);const p=decrypt(path).then(b=>{const u=URL.createObjectURL(new Blob([b],{type:path.endsWith('/original.bin')?'application/pdf':'image/webp'}));cache.set(path,u);pending.delete(path);if(cache.size>145){for(const [old,blob] of cache){if(old.endsWith('/cover.bin')||old===path||(current&&old===assetPath(current,page)))continue;URL.revokeObjectURL(blob);cache.delete(old);break}}return u}).catch(e=>{pending.delete(path);throw e});pending.set(path,p);return p}
const assetPath=(b,n)=>'assets/'+b.id+'/'+n+'.bin';
let thumbObserver;
function lazyCovers(){if(thumbObserver)thumbObserver.disconnect();thumbObserver=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;const img=e.target;thumbObserver.unobserve(img);asset(assetPath({id:img.dataset.id},'cover')).then(url=>{img.src=url;img.classList.add('loaded')}).catch(()=>{img.nextElementSibling.textContent='封面暂未加载，点击阅读'})}},{rootMargin:'250px'});document.querySelectorAll('.cover img').forEach(i=>thumbObserver.observe(i))}
function saveProgress(){progress[current.id]={page,time:Date.now()};localStorage.setItem('architecture-progress',JSON.stringify(progress))}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('architecture-favorites',JSON.stringify([...favorites]));if(current&&current.id===id)$('star').textContent=favorites.has(id)?'♥':'♡';draw();toast(favorites.has(id)?'已加入收藏':'已取消收藏')}
function draw(){const q=$('search').value.toLowerCase().trim();let a=books.filter(b=>(!activeCategory||b.category===activeCategory)&&(!onlyFavorites||favorites.has(b.id))&&(!q||[b.title,b.original,b.group,b.search].join(' ').toLowerCase().includes(q)));if($('sort').value==='name')a.sort((a,b)=>a.title.localeCompare(b.title,'zh'));if($('sort').value==='pages')a.sort((a,b)=>b.count-a.count);$('resultCount').textContent=a.length+' 份 · '+a.reduce((s,b)=>s+b.count,0).toLocaleString()+' 页';$('empty').hidden=!!a.length;$('grid').innerHTML=a.map(b=>{const p=progress[b.id]?.page;return `<article class="card"><button class="cover" data-open="${b.id}" aria-label="翻阅 ${esc(b.title)}">${b.sourcePasswordRequired?'<span class="placeholder">原 PDF 需要打开密码</span>':`<img data-id="${b.id}" alt="${esc(b.title)}封面"><span class="placeholder">ARCHITECTURE / ${esc(b.group)}</span>`}<span class="read">翻开作品集 ↗</span>${p?`<i class="progress" style="width:${100*p/b.count}%"></i>`:''}</button><h2>${esc(b.title)}</h2><div class="meta"><span>${esc(b.group)}</span><span>· ${b.sourcePasswordRequired?'需要密码':b.count+' 页'}</span>${p?`<span>· 读到 ${p}</span>`:''}</div><button class="save" data-save="${b.id}" aria-label="${favorites.has(b.id)?'取消收藏':'收藏'} ${esc(b.title)}">${favorites.has(b.id)?'♥':'♡'}</button></article>`}).join('');lazyCovers();updateContinue()}
function updateContinue(){const latest=Object.entries(progress).filter(([id])=>books.some(b=>b.id===id)).sort((a,b)=>b[1].time-a[1].time)[0];$('continue').hidden=!latest;if(latest){const b=books.find(b=>b.id===latest[0]);$('continue').innerHTML='<span>上次读到 <b>'+esc(b.title)+'</b> · 第 '+latest[1].page+' 页</span><button data-open="'+b.id+'">继续阅读 →</button>'}}
function resizePage(){if(!current||current.sourcePasswordRequired)return;const [w,h]=current.pages[page-1],v=$('viewport'),mode=$('zoom').value,pad=innerWidth<600?20:44;let width;if(mode==='fit')width=Math.min(v.clientWidth-pad,(v.clientHeight-pad)*w/h);else if(mode==='width')width=v.clientWidth-pad;else width=(v.clientWidth-pad)*Number(mode)/100;$('pageImage').style.width=Math.max(80,width)+'px';$('pageImage').style.height=Math.max(80,width)*h/w+'px';}
async function showPage(n){if(!current||current.sourcePasswordRequired)return;page=Math.max(1,Math.min(current.count,Number(n)||1));const request=++sequence,b=current;$('pageNo').value=page;$('pageOf').textContent='/ '+b.count;$('prev').disabled=page===1;$('next').disabled=page===b.count;$('pageImage').classList.add('loading');$('pageImage').alt=b.title+'，第 '+page+' 页';$('pageStatus').textContent='正在读取第 '+page+' 页…';$('viewport').scrollTo(0,0);resizePage();document.querySelectorAll('#thumbs button').forEach(e=>e.classList.toggle('active',Number(e.dataset.page)===page));const nav=document.querySelector('#thumbs .active');nav?.scrollIntoView({block:'nearest'});saveProgress();
 try{const u=await asset(assetPath(b,page));if(request!==sequence)return;$('pageImage').src=u;$('pageImage').classList.remove('loading');$('pageStatus').textContent='';if(page<b.count)asset(assetPath(b,page+1)).catch(()=>{});if(page>1)asset(assetPath(b,page-1)).catch(()=>{})}catch(e){if(request===sequence){$('pageStatus').innerHTML='这一页没有加载成功。<br>点击上一页再返回，或稍后重试。';console.warn('Page load failed',b.id,page,e.message)}}}
function openBook(id){const b=books.find(x=>x.id===id);if(!b)return;current=b;$('reader').querySelector('iframe')?.remove();$('paper').hidden=false;$('thumbs').hidden=false;document.querySelector('.readerbottom').hidden=false;if(b.sourcePasswordRequired){openProtected(b);return;}$('bookTitle').textContent=b.title;$('bookGroup').textContent=b.group+' · '+b.count+' 页';$('star').textContent=favorites.has(id)?'♥':'♡';$('info').hidden=true;$('info').innerHTML='<b>'+esc(b.original)+'</b><br>'+esc(b.category)+' / '+esc(b.group)+'<br>原 PDF '+(b.size/1e6).toFixed(1)+' MB · '+b.count+' 页<br>网页为完整逐页预览，原始文件仍保留。';$('thumbs').innerHTML=Array.from({length:b.count},(_,i)=>'<button data-page="'+(i+1)+'" aria-label="第 '+(i+1)+' 页">'+String(i+1).padStart(2,'0')+'</button>').join('');if(!$('reader').open)$('reader').showModal();document.body.style.overflow='hidden';$('zoom').value='fit';showPage(progress[id]?.page||1)}
async function openProtected(b){const req=++sequence;$('bookTitle').textContent=b.title;$('bookGroup').textContent='原 PDF 需要密码 · 请在阅读器中输入';$('star').textContent=favorites.has(b.id)?'♥':'♡';$('info').hidden=true;$('info').textContent=b.original+' · 原文件设有打开密码。';$('paper').hidden=true;$('thumbs').hidden=true;document.querySelector('.readerbottom').hidden=true;if(!$('reader').open)$('reader').showModal();document.body.style.overflow='hidden';const frame=document.createElement('iframe');frame.title='需要原文件密码的 PDF';frame.style.cssText='width:100%;height:100%;min-height:65vh;border:0;background:white';$('viewport').appendChild(frame);try{const url=await asset(assetPath(b,'original'));if(sequence===req)frame.src=url;}catch{toast('原文件加载失败，请稍后重试')}}
function closeBook(){$('reader').close();document.body.style.overflow='';sequence++;current=null;draw()}
$('grid').addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){toggleFavorite(save.dataset.save);return}const open=e.target.closest('[data-open]');if(open)openBook(open.dataset.open)});$('continue').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openBook(b.dataset.open)});
$('search').addEventListener('input',draw);$('sort').addEventListener('change',draw);$('favoriteFilter').onclick=()=>{onlyFavorites=!onlyFavorites;$('favoriteFilter').setAttribute('aria-pressed',onlyFavorites);$('favoriteFilter').textContent=onlyFavorites?'♥ 已收藏':'♡ 收藏';draw()};$('close').onclick=closeBook;$('reader').addEventListener('cancel',e=>{e.preventDefault();closeBook()});$('prev').onclick=()=>showPage(page-1);$('next').onclick=()=>showPage(page+1);$('pageNo').onchange=()=>showPage($('pageNo').value);$('zoom').onchange=resizePage;window.addEventListener('resize',resizePage);$('star').onclick=()=>current&&toggleFavorite(current.id);$('infoToggle').onclick=()=>{$('info').hidden=!$('info').hidden};$('thumbs').onclick=e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)};
$('openImage').onclick=async()=>{if(!current)return;const w=window.open('about:blank','_blank');try{w.location=await asset(assetPath(current,page))}catch{w.close();toast('图片暂时无法打开')}};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(current){if(e.key==='ArrowRight'){e.preventDefault();showPage(page+1)}if(e.key==='ArrowLeft'){e.preventDefault();showPage(page-1)}}else if(e.key==='/'){e.preventDefault();$('search').focus()}});
function extractKey(v){try{if(v.includes('#'))v=new URL(v).hash.slice(1);if(v.includes('k='))v=new URLSearchParams(v).get('k');return v.trim()}catch{return ''}}
async function unlock(v){$('gateText').textContent='正在打开收藏…';$('unlock').hidden=true;try{const raw=extractKey(v);if(!/^[0-9a-f]{64}$/i.test(raw))throw new Error('missing');cryptoKey=await crypto.subtle.importKey('raw',new Uint8Array(raw.match(/../g).map(h=>parseInt(h,16))),'AES-GCM',false,['decrypt']);books=JSON.parse(new TextDecoder().decode(await decrypt('library.bin')));localStorage.setItem('architecture-key',raw);$('gate').hidden=true;$('library').hidden=false;$('total').textContent=books.length;$('pagesTotal').textContent=books.reduce((s,b)=>s+b.count,0).toLocaleString()+' 页设计记录';const cats=[...new Set(books.map(b=>b.category))];$('filters').innerHTML='<button class="active" data-category="">全部 <small>'+books.length+'</small></button>'+cats.map(c=>'<button data-category="'+esc(c)+'">'+esc(c)+' <small>'+books.filter(b=>b.category===c).length+'</small></button>').join('');$('filters').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;activeCategory=b.dataset.category;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));draw()};draw()}catch(e){$('gateText').textContent='请使用完整阅览链接打开，或粘贴访问码。';$('unlock').hidden=false}}
$('unlock').onsubmit=e=>{e.preventDefault();unlock($('keyInput').value)};unlock(new URLSearchParams(location.hash.slice(1)).get('k')||localStorage.getItem('architecture-key')||'');
